issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    - if-return
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec

linters:
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - gocognit
    - gocritic
    - gofumpt
    - gosec
    - lll
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars

linters-settings:
  gocognit:
    min-complexity: 10

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - paramTypeCombine
      - ptrToRefParam

  gofumpt:
    module-path: github.com/rliebz/ghost

  gosec:
    excludes:
      - G104 # duplicate of errcheck
      - G307 # duplicate of errcheck

  govet:
    enable-all: true
    disable:
      - fieldalignment

  lll:
    line-length: 100
    tab-width: 2

  misspell:
    locale: US

  nakedret:
    max-func-lines: 0

  revive:
    confidence: 0
